#Config File for AccessPopup by RaspberryConnect.com
#v0.1
#used by installconfig.sh

#####Wifi Enabling
#For systems that manage Wifi availability separately
#If wifi is disabled in Network Manager, then it will be enabled automatically 
#when AccessPopup is run next, usually every 2 minutes.
#if set to 'n' then the wifi will stay off and no Access Point will be generated 
#and no Network Connection will be available.
re_enable_wifi='y'

#### AccessPopup Access Point Settings
#Changes will only take effect when a new profile is created
#Delete the existing profile with;
#nmcli con del AccessPopup
#When the AccessPopup script next creates an Access Point the changed details will be used.

#Default Wifi Device for both Access Point and Network Connections
wdev0='wlan0'

#SSID for the Access Point
ap_ssid='AccessPopup'

#Password for the Access Point
ap_pw='1234567890'

#Access Point ip address
ap_ip='192.168.50.5/24'

#Access Point gateway ip address
#The first 3 numbers should match the number for the "Access Point ip Address" ###.###.##
#leave the fourth number as 254
ap_gate='192.168.50.254'

